# Generated by Django 2.2.7 on 2019-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='first_day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنیه'), ('3', 'سه شنبه'), ('4', 'چهارشنیه')], max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنیه'), ('3', 'سه شنبه'), ('4', 'چهارشنیه')], max_length=1),
        ),
    ]
